import Head from 'next/head';
import Layout from '../widgets/layout';

export default function Home() {
    return (
        <>
            <Head>
                <title>Visit Malang</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <Layout>
                <main className='h-screen'>Tes</main>
            </Layout>
        </>
    );
}
